[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "pydantic-ai-slim>=0.1.3",
    "pydantic-ai-slim[mcp]>=0.1.3",
    "pydantic-ai-slim[openai]"
]
